Added "source" annotation to the Task metadata.
openshift-pipelines/catalog-cd pull request #5
Opened 2024-01-25 14:38 UTC by Senjuti256

Signed off :- @Senjuti256 <sde@redhat.com>

2024-01-25 14:57 UTC, vdemeester commented on internal/catalog/catalog.go
> +	annotations["source"] = fmt.Sprintf("%s/releases/download/%s", strings.TrimPrefix(url, "https://www.github.com/"), version)
- I think we could just print out the repository URI (so https://github.com/openshift-pipelines/task-containers for example)
- Why do we trim the github.com part ?

2024-01-25 14:57 UTC, vdemeester commented on internal/catalog/catalog.go
> +					}
There could be multiple tasks we pull from there. I think an example here is `task-containers`. I think this would try to mutate a `task-containers.yaml` file that doesn't exists, wouldn't it ?

2024-01-29 11:57 UTC, Senjuti256 commented on internal/catalog/catalog.go
> +					}
I was assuming that people will by default understand that the prefix will be "https://www.github.com/" .

2024-01-29 11:58 UTC, Senjuti256 commented on internal/catalog/catalog.go
> +	annotations["source"] = fmt.Sprintf("%s/releases/download/%s", strings.TrimPrefix(url, "https://www.github.com/"), version)
I was assuming that people will by default understand that the prefix will be "https://www.github.com/" .

2024-01-29 13:47 UTC, vdemeester commented
```bash
$ catalog-cd catalog generate --config ./externals.yaml .
Generating a catalog from ./externals.yaml in .
# Fetching resources from golang-tasks
## Fetching version 0.4.0
Error traversing task directory tasks/golang-tasks/0.4.0: lstat tasks/golang-tasks/0.4.0: no such file or directory
## Fetching version 0.5.0
Error traversing task directory tasks/golang-tasks/0.5.0: lstat tasks/golang-tasks/0.5.0: no such file or directory
```

2024-02-06 11:03 UTC, vdemeester requested changes
So few things:

- For some reason, the code indentation is wrong (files need to go through `gofmt`.. usually editors automatically do that)
- It did skip some Tasks (see output below)
- URL should point to the repository, not the resource.tar.gz imo (`source: https://github.com/openshift-pipelines/task-maven/releases/download/v0.1.0/resources.tar.gz` should probably be `source: https://github.com/openshift-pipelines/task-maven/`)

```
Generating a catalog from ../tektoncd-catalog/externals.yaml in /tmp/foo
# Fetching resources from task-git
## Fetching version 0.2.0
Adding source annotation to Task YAML file: /tmp/foo/tasks/task-git/0.2.0/task-git.yaml
## Fetching version 0.1.0
Adding source annotation to Task YAML file: /tmp/foo/tasks/task-git/0.1.0/task-git.yaml
# Fetching resources from task-maven
## Fetching version 0.1.0
Adding source annotation to Task YAML file: /tmp/foo/tasks/task-maven/0.1.0/task-maven.yaml
# Fetching resources from task-openshift
# Fetching resources from task-containers
## Fetching version 0.2.0
## Fetching version 0.1.1
```
It didn't do anything for `task-containers` tasks.

2024-02-27 11:14 UTC, closed without merging